version: '3.6'
services:
  keycloak:
    container_name: rems_dev_keycloak
    command: 'start-dev --import-realm'
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - rems_dev_keycloak-data:/opt/keycloak/data/
      - '../test-ehr/src/main/resources/ClientFhirServerRealm.json:/opt/keycloak/data/import/ClientFhirServerRealm.json'
    build:
      context: ../test-ehr
      dockerfile: Dockerfile.keycloak

  test-ehr:
    container_name: rems_dev_test-ehr
    ports:
      - '8080:8080'
      - "8081:8081"
    build:
      context: ../test-ehr
    environment:
      - oauth_token=http://host.docker.internal:8180/realms/ClientFhirServer/protocol/openid-connect/token
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pims_remsadmin_mongo:
    image: mongo
    container_name: rems_dev_pims-remsadmin-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: rems-admin-pims-root
      MONGO_INITDB_ROOT_PASSWORD: rems-admin-pims-password
    volumes:
      - rems_dev_pims_remsadmin_mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  request-generator:
    build:
      context: ../request-generator
    container_name: rems_dev_request-generator
    environment:
      - REACT_APP_EHR_SERVER_TO_BE_SENT_TO_REMS_ADMIN_FOR_PREFETCH=http://host.docker.internal:8080/test-ehr/r4
    ports:
      - "3000:3000"
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rems-smart-on-fhir:
    build:
      context: ../rems-smart-on-fhir
    container_name: rems_dev_rems-smart-on-fhir
    ports:
      - "4040:4040"
      - "4041:4041"

  rems-administrator:
    build:
      context: '../rems-admin'
    container_name: rems_dev_rems-administrator
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      VSAC_API_KEY: ${VSAC_API_KEY}
      MONGO_URL: mongodb://rems-user:pass@pims_remsadmin_mongo:27017

  rems-administrator2:
    build:
      context: '../rems-admin'
    container_name: rems_dev_rems-administrator2
    ports:
      - "8095:8095"
      - "8096:8096"
    environment:
      VSAC_API_KEY: ${VSAC_API_KEY}
      MONGO_URL: mongodb://rems-user:pass@pims_remsadmin_mongo:27017
      PORT: 8095

  pims:
    build:
      context: ../pims
    container_name: rems_dev_pims
    ports:
      - "5050:5050"
      - "5051:5051"
    environment:
      REMS_ADMIN_FHIR_URL: http://rems-administrator:8090/4_0_0
      MONGO_URL: mongodb://pims_remsadmin_mongo:27017/pims
      EHR_RXFILL_URL: http://host.docker.internal:8080/test-ehr/script/rxfill

  rems-intermediary:
    build:
      context: '../rems-intermediary'
    container_name: rems_dev_rems-intermediary
    environment:
      MONGO_URL: mongodb://rems-user:pass@pims_remsadmin_mongo:27017
      VITE_AUTH: http://keycloak:8080
    ports:
      - "3003:3003"

volumes:
  rems_dev_keycloak-data:
  rems_dev_pims_remsadmin_mongo:

