version: '3.6'
services:
  keycloak:
    container_name: rems_prod_keycloak
    command: 'start-dev --import-realm'
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - rems_prod_keycloak-data:/opt/keycloak/data/
    image: codexrems/keycloak:1.1

  # Create test-ehr container
  test-ehr: # Name of our service
    container_name: rems_prod_test-ehr
    ports: # Port binding to host from docker container
      - '8080:8080' # Bind port 3000 of host to 3000 of container
    image: codexrems/test-ehr:1.1
    environment:
      - oauth_token=http://host.docker.internal:8180/realms/ClientFhirServer/protocol/openid-connect/token
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Create crd request generator container
  request-generator: # Name of our service
    image: codexrems/request-generator:1.1
    container_name: rems_prod_request-generator
    environment:
      - REACT_APP_EHR_SERVER_TO_BE_SENT_TO_REMS_ADMIN_FOR_PREFETCH=http://host.docker.internal:8080/test-ehr/r4
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Create rems-smart-on-fhir container
  rems-smart-on-fhir:
    image: codexrems/rems-smart-on-fhir:1.1
    container_name: rems_prod_rems-smart-on-fhir
    ports:
      - "4040:4040"

  # Create rems container
  rems-administrator: # Name of our service
    image: codexrems/rems-administrator:1.1
    container_name: rems_prod_rems-administrator
    ports: # Port binding to host from docker container
      - "8090:8090"
    environment:
      VSAC_API_KEY: ${VSAC_API_KEY}
      MONGO_URL: mongodb://rems-user:pass@pims_remsadmin_mongo:27017

  rems-administrator2: # Name of our service
    image: codexrems/rems-administrator:1.1
    container_name: rems_prod_rems-administrator2
    ports: # Port binding to host from docker container
      - "8095:8095"
    environment:
      VSAC_API_KEY: ${VSAC_API_KEY}
      MONGO_DB_NAME: remsadmin2
      MONGO_URL: mongodb://rems-user:pass@pims_remsadmin_mongo:27017
      PORT: 8095

  # Create pims admin container
  pims_remsadmin_mongo:
    image: mongo
    container_name: rems_prod_pims-remsadmin-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: rems-admin-pims-root
      MONGO_INITDB_ROOT_PASSWORD: rems-admin-pims-password
    volumes:
      - rems_prod_pims_remsadmin_mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  # Create pims container
  pims:
    image: codexrems/pims:1.1
    container_name: rems_prod_pims
    environment:
      REMS_ADMIN_FHIR_URL: http://rems-administrator:8090/4_0_0
      MONGO_URL: mongodb://pims_remsadmin_mongo:27017/pims
      EHR_RXFILL_URL: http://host.docker.internal:8080/test-ehr/script/rxfill
    ports:
      - "5050:5050"
      - "5051:5051"

  # add in once intermediary once ci/cd pipeline task is completed and published images exist 
  # rems-intermediary:
  #   image: codexrems/rems-intermediary:1.1
  #   container_name: rems_prod_rems-intermediary
  #   environment:
  #     MONGO_URL: mongodb://intermediary-user:pass@pims_remsadmin_mongo:27017
  #   ports:
  #     - "3003:3003"


volumes:
  rems_prod_keycloak-data:
  rems_prod_pims_remsadmin_mongo:


