name: Mongo Docker Image CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mongo-docker-cd: 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta data
      id: docker-meta-data
      uses: docker/metadata-action@v4
      with:
        images: codexrems/mongo
        flavor: latest=false

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Build and push Mongo Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile.mongo
        push: true
        tags: codexrems/mongo:latest
        labels: ${{ steps.docker-meta-data.outputs.labels }}

    
