name: Playwright Tests
on:
  push:
    branches: [ main, dev, tagging-docker-compose ]
  pull_request:
    branches: [ main, dev, tagging-docker-compose ]
  workflow_dispatch:
    inputs:
      rems-setup-branch:
        description: 'rems set up branch'     
        required: true
        default: 'main'
      request-generator-branch:
        description: 'request generator branch'     
        required: true
        default: 'main'  
      pims-branch:
        description: 'pims branch'     
        required: true
        default: 'main'      
      rems-admin-branch:
        description: 'rems admin branch'     
        required: true
        default: 'main'    
      rems-smart-on-fhir-branch:
        description: 'rems smart on fhir branch'     
        required: true
        default: 'main'   
      rems-test-ehr-branch:
        description: 'rems test-ehr branch'     
        required: true
        default: 'main'   

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: mcode/rems-setup
          path: rems-setup
          ref: ${{ github.event.inputs.rems-setup-branch }}

      - name: Checkout test-ehr repo
        uses: actions/checkout@v4
        with:
          repository: mcode/test-ehr
          path: test-ehr
          ref: ${{ github.event.inputs.rems-test-ehr-branch }}

      - name: Checkout request-generator repo
        uses: actions/checkout@v4
        with:
          repository: mcode/request-generator
          path: request-generator
          ref: ${{ github.event.inputs.request-generator-branch }}

      - name: Checkout rems-admin repo
        uses: actions/checkout@v4
        with:
          repository: mcode/rems-admin
          path: rems-admin
          submodule: true
          ref: ${{ github.event.inputs.rems-admin-branch }}

      - name: Checkout pims repo
        uses: actions/checkout@v4
        with:
          repository: mcode/pims
          path: pims
          ref: ${{ github.event.inputs.pims-branch }}

      - name: Checkout rems-smart-on-fhir repo
        uses: actions/checkout@v4
        with:
          repository: mcode/rems-smart-on-fhir
          path: rems-smart-on-fhir
          submodule: true
          ref: ${{ github.event.inputs.rems-smart-on-fhir-branch }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Check docker-compose
        run: docker-compose --version 

      - name: Start containers
        run: docker-compose -f docker-compose-local-build.yml up -d --wait 

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
